FROM bittles999/hassio-gst-downloaded

# update compile script
COPY docker/build-gstreamer/compile /compile

#ARG WEBKIT_USE_SCCACHE=0

ENV DEBUG=false
ENV OPTIMIZATIONS=true

RUN ["/compile"]

FROM bittles999/hassio-gst-base

COPY --from=0 /compiled-binaries /